name: CI – Build & Push Dev Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Metadata for Dev
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/project-butterfly-ai
        tags: |
          type=raw,value=latest-dev
          type=sha

    - name: Build and Push Dev Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}