name: CI – Build & Push to GHCR

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1 ▸ Check out code
    - uses: actions/checkout@v4

    # 2 ▸ Buildx for multi-arch and cache
    - uses: docker/setup-buildx-action@v3

    # 3 ▸ Log in to GitHub Container Registry
    - name: Login to GHCR
      id: login
      env:
        CR_PAT: ${{ secrets.CR_PAT }}          # safe to expose as env
      run: |
        if [ -n "$CR_PAT" ]; then
          echo "$CR_PAT" | docker login ghcr.io \
            -u "${{ github.actor }}" --password-stdin
          echo "logged=true" >> "$GITHUB_OUTPUT"
        else
          echo "No CR_PAT secret – build will run but image won't be pushed."
        fi

    # 4 ▸ Generate image tags & labels
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=sha

    # 5 ▸ Build (and push only if login successful)
    - uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ steps.login.outputs.logged == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # 6 ▸ Optional smoke test
    - name: Smoke-test container
      run: docker run --rm ${{ steps.meta.outputs.tags }} --help || true