# .github/workflows/release.yml – Auto-versioning for prod (vX.X.X)
name: Release – Auto-Version & Push to GHCR

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type: patch, minor, or major"
        required: true
        default: "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get latest prod tag and bump version
      id: version
      run: |
        bump="${{ github.event.inputs.bump }}"
        latest=$(git tag -l 'v*' --sort=-v:refname | head -n1)
        echo "Latest prod tag: $latest"
        if [[ "$latest" == "" ]]; then
          new="1.0.0"
        else
          ver=${latest#v}
          IFS='.' read -r major minor patch <<< "$ver"
          if [[ "$bump" == "minor" ]]; then
            minor=$((minor+1)); patch=0
          elif [[ "$bump" == "major" ]]; then
            major=$((major+1)); minor=0; patch=0
          else
            patch=$((patch+1))
          fi
          new="${major}.${minor}.${patch}"
        fi
        echo "new_version=$new" >> $GITHUB_OUTPUT
        echo "::notice title=Release Docker Version::v$new"

    - name: Create prod tag
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag v${{ steps.version.outputs.new_version }}
        git push origin v${{ steps.version.outputs.new_version }}

    - uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Metadata for GHCR Release
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=v${{ steps.version.outputs.new_version }}
          type=raw,value=latest
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.description="Project Butterfly AI official release"
          org.opencontainers.image.licenses=MIT

    - name: Build & Push Release Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.version.outputs.new_version }}
        generate_release_notes: true
